// Generated by gencpp from file msg_generatorstd_msgs/VelodyneSensor.msg
// DO NOT EDIT!


#ifndef MSG_GENERATORSTD_MSGS_MESSAGE_VELODYNESENSOR_H
#define MSG_GENERATORSTD_MSGS_MESSAGE_VELODYNESENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msg_generatorstd_msgs
{
template <class ContainerAllocator>
struct VelodyneSensor_
{
  typedef VelodyneSensor_<ContainerAllocator> Type;

  VelodyneSensor_()
    : header()
    , angle(0.0)
    , dist()  {
    }
  VelodyneSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle(0.0)
    , dist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angle_type;
  _angle_type angle;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> const> ConstPtr;

}; // struct VelodyneSensor_

typedef ::msg_generatorstd_msgs::VelodyneSensor_<std::allocator<void> > VelodyneSensor;

typedef boost::shared_ptr< ::msg_generatorstd_msgs::VelodyneSensor > VelodyneSensorPtr;
typedef boost::shared_ptr< ::msg_generatorstd_msgs::VelodyneSensor const> VelodyneSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator1> & lhs, const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle == rhs.angle &&
    lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator1> & lhs, const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_generatorstd_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99daecf91b2d1033269eb2b61c4371c1";
  }

  static const char* value(const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99daecf91b2d1033ULL;
  static const uint64_t static_value2 = 0x269eb2b61c4371c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_generatorstd_msgs/VelodyneSensor";
  }

  static const char* value(const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"\n"
"float32 angle\n"
"float32[] dist\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelodyneSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_generatorstd_msgs::VelodyneSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "dist[]" << std::endl;
    for (size_t i = 0; i < v.dist.size(); ++i)
    {
      s << indent << "  dist[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GENERATORSTD_MSGS_MESSAGE_VELODYNESENSOR_H
